name: Test updated tasks
on:
  - push
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - uses: actions/checkout@v4
    - id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        files: |
          **/tasks/**
        dir_names_include_files: |
          **/tasks/*
        dir_names: true
        dir_names_max_depth: 3
    - name: Changed files
      env:
        CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        for file in ${CHANGED_FILES}; do
          echo "$file"
        done
    - if: steps.changed-files.outputs.any_changed == 'true'
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - if: steps.changed-files.outputs.any_changed == 'true'
      run: | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        flake8 ${{ steps.changed-files.outputs.all_changed_files }}
      continue-on-error: true
    - name: Check with mypy
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        mypy ${{ steps.changed-files.outputs.all_changed_files }}
      continue-on-error: true
    - name: Run pytest
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        pytest ${{ steps.changed-files.outputs.all_changed_files }}
      continue-on-error: true